name: Generate SpiceDB nuget package

on:
  workflow_dispatch:
    inputs:
      client_version:
        description: "Version number for the client"
        required: true

jobs:
  generate-csharp-client:
    runs-on: ubuntu-latest
    permissions:
      packages: write
      contents: read
      
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        
      - name: Package
        run: |
          dotnet pack ./SpiceDbClient/SpiceDbClient.csproj --configuration Release --output ${{github.workspace}}/NuGet
      
#       - name: Login
#         run: dotnet nuget add source --username ${{ github.actor }} --password ${{ secrets.GITHUB_TOKEN }} --store-password-in-clear-text --name GH "https://nuget.pkg.github.com/sains1/index.json"
        
      - name: Publish
        run: dotnet nuget push ${{github.workspace}}/NuGet/*.nupkg  --source "GH" --api-key ${{secrets.GITHUB_TOKEN}}
